
services:
  # Golang gRPC Service
  app:
    build:
      context: .
      dockerfile: Dockerfile # Dockerfile to build your Golang app
    ports:
      - "50051:50051"  # gRPC service port
    restart: always
    environment:
      - GO_DIRECTORY=/home/user/FreePDM
      - GO_WORKDIR=/home/user/FreePDM/cmd/pdmserver

      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=yourusername
      - DB_PASSWORD=yourpassword
      - DB_NAME=FreePDM
    depends_on:
      - db
    volumes:
      - ./app:/go/src/app  # Mount your app source code for easier development
      - ./data:/app/data
      - ./logs:/app/logs
      - /samba/vaultsdata:/samba/vaultsdata
    networks:
      - app-network
    command: /app/freepdm

  # PostgreSQL Database
  db:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: FreePDM
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist database data
    networks:
      - app-network

  samba:
    image: ghcr.io/servercontainers/samba:latest
    restart: always
    network_mode: host
    cap_add:
      - CAP_NET_ADMIN
    environment:
      TZ: Europe/Amsterdam

      SAMBA_CONF_LOG_LEVEL: 3

      GROUP_sambashare: 125

      ACCOUNT_user: passwd
      UID_user: 1000
      GROUPS_user: sambashare

      ACCOUNT_josh: josh1
      UID_josh: 1001
      GROUPS_josh: sambashare

      ACCOUNT_user1: passwd1
      UID_user1: 1001
      GROUPS_user1: sambashare

      SAMBA_VOLUME_CONFIG_vaults: |
        [vaults]
          path = /samba/vaults
          valid users = user josh user1
          guest ok = no
          browseable = yes
          read only = no
          writeable = yes
          create mask = 0660
          directory mask = 2770
    volumes:
      - /samba/vaults:/samba/vaults

# Volumes
volumes:
  db_data:  # Persist data for PostgreSQL

# Networks
networks:
  app-network:  # Shared network for all services
