
services:
  # Golang Service
  app:
    image: freepdm-app
    container_name: freepdm
    build:
      context: .
      dockerfile: Dockerfile # Dockerfile to build your Golang app
    ports:
      - "8080:8080"  # json service port
    restart: always
    environment:
      - FREEPDM_DIR=${FREEPDM_DIR}
      - GO_DIRECTORY=${FREEPDM_DIR}
      - GO_WORKDIR=${FREEPDM_DIR}/cmd/pdmserver
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=yourusername
      - DB_PASSWORD=yourpassword
      - DB_NAME=FreePDM
    depends_on:
      - db
    volumes:
      - ./app:/go/src/app  # Mount your app source code for easier development
      - ./data:${FREEPDM_DIR}/data
      - ./logs:${FREEPDM_DIR}/logs
    networks:
      - app-network
    command: /app/freepdm

  # PostgreSQL Database
  db:
    image: postgres:14
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: yourusername
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: FreePDM
    volumes:
      - db_data:/var/lib/postgresql/data  # Persist database data
    networks:
      - app-network

  samba:
    image: ghcr.io/servercontainers/samba:latest
    container_name: samba
    restart: always
    network_mode: host
    cap_add:
      - CAP_NET_ADMIN
    environment:
      TZ: Europe/Amsterdam

      SAMBA_CONF_LOG_LEVEL: 1

      GROUP_sambashare: 125

      ACCOUNT_user: passwd
      UID_user: 1000
      GROUPS_user: sambashare

      ACCOUNT_josh: josh1
      UID_josh: 1001
      GROUPS_josh: sambashare

      SAMBA_VOLUME_CONFIG_vaults: |
        [vaults]
          path = /home/user/vaults
          valid users = user josh
          guest ok = no
          browseable = yes
          read only = no
          writeable = yes
          create mask = 0660
          directory mask = 2770
    volumes:
      - /home/user/vaults:/home/user/vaults

# Volumes
volumes:
  db_data:  # Persist data for PostgreSQL

# Networks
networks:
  app-network:  # Shared network for all services
